version: '3'

services:
  php:
    build: docker/php
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db

  db:
    image: mongo:5.0
    command: mongod --wiredTigerCacheSizeGB 0.25
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512M
    volumes:
      - db:/data/db

  mkdocs:
    image: polinux/mkdocs
    volumes:
      - .:/workdir/mkdocs

volumes:
  db:
    driver: local
