name: docs-deployment-test

on:
  push:
    branches:
      - docs/update-workflow
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docs'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
