name: docs-deployment-test

on:
  pull_request:
    branches:
      - v3.x
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        run: cd docs
        uses: actions/setup-node@v3
        with:
          working-directory: docs
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
